# The name of the network
name: mainnet
# URL Prefix for this network
# For example, url_prefix is "example", register at "gradecoin.xyz/example/register"
url_prefix: ""
# List of users who can register
# CSV file: userID,password
# First line is ignored
preapproved_users: "students.csv"
# Valid blocks should have this many transactions
block_transaction_count: 4
# How many zero hexadecimal characters should a correct hash start with?
hash_zeros: 6
# Bonus awarded after registration
register_bonus: 20
# Coinbase reward
block_reward: 2
# Transaction limits
tx_upper_limit: 4
tx_lower_limit: 1
# Transaction traffic reward
tx_traffic_reward: 1
